// import type { NextAuthOptions } from "next-auth";
import type { NextAuthOptions } from "next-auth";
import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";

import { auth } from "@/firebase/admin";

import firebaseAdapter from "./firebaseAdapter";

export const authOptions: NextAuthOptions = {
  adapter: firebaseAdapter, // firebase adapter config in firebaseAdapter.ts file
  callbacks: {
    async jwt({ token, user }) {
      return { ...token, ...user };
    },
    // sessionにJWTトークンからのユーザ情報を格納
    async session({ session, token }) {
      session.user.emailVerified = token.emailVerified;
      session.user.uid = token.uid;
      return session;
    },
  },
  providers: [
    CredentialsProvider({
      authorize: async ({ idToken }: any, _req) => {
        if (idToken) {
          try {
            const decoded = await auth.verifyIdToken(idToken);

            return { ...decoded };
          } catch (err) {
            console.error(err);
          }
        }
        return null;
      },
      credentials: {},
    }),
  ], // all providers in providers folder
  secret: process.env.NEXT_AUTH_SECRET, // this command can be generated by command "openssl rand -base64 32"
  session: {
    strategy: "jwt",
  },
};

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
