import "@/styles/globals.scss";

import { Provider } from "jotai";
import { redirect } from "next/navigation";

import { Header } from "@/component/Header";
import { Navigation } from "@/component/Navigation";
import { create_ServerClient } from "@/utils/supabase/server";

export const metadata = {
  title: "Tought Keeper",
  description: "Generated by Next.js",
};

export default async function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = create_ServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return redirect("/auth/login");
  }
  return (
    <Provider>
      <body>
        <Header />
        <div className="flex justify-center">
          <div className=" bg-lightGray/20">
            <Navigation />
          </div>
          <div className="min-h-screen w-full">{children}</div>
        </div>
      </body>
    </Provider>
  );
}
