import "@/styles/globals.scss";

import { Header } from "@/component/Header";
import { Navigation } from "@/component/Navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex justify-center">
          <div className=" bg-tomato/5">
            <Navigation />
          </div>
          <div className="min-h-screen w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
