import "@/styles/globals.scss";

import { Header } from "@/component/Header";
import { Navigation } from "@/component/Navigation";
import SessionProvider from "@/provider/SessionProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body>
          <Header />
          <div className="flex">
            <div className=" bg-tomato/5">
              <Navigation />
            </div>
            <div className="min-h-screen flex-1">{children}</div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
