import "@/styles/globals.scss";

import { redirect } from "next/navigation";

import { createSupabaseServerClient } from "@/app/utils/supabase/server";
import { Header } from "@/component/Header";
import { Navigation } from "@/component/Navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createSupabaseServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex justify-center">
          <div className=" bg-lightGray/20">
            <Navigation />
          </div>
          <div className="min-h-screen w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
