import "@/styles/globals.scss";

import { redirect } from "next/navigation";

import { createSupabaseServerClient } from "@/app/utils/supabase/server";
import { Header } from "@/component/Header";
import { Navigation } from "@/component/Navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createSupabaseServerClient();

  try {
    const { data, error } = await supabase.auth.getUser();

    if (error) {
      console.error("Auth error:", error);
      // Continue with the login page if there's an error
      return (
        <html lang="en">
          <body>
            <Header />
            <div className="flex justify-center">
              <div className=" bg-lightGray/20">
                <Navigation />
              </div>
              <div className="min-h-screen w-full">{children}</div>
            </div>
          </body>
        </html>
      );
    }

    if (data?.user) {
      return redirect("/");
    }
  } catch (error) {
    console.error("Unexpected error:", error);
    // Continue with the login page if there's an unexpected error
  }

  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex justify-center">
          <div className=" bg-lightGray/20">
            <Navigation />
          </div>
          <div className="min-h-screen w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
